In [72]:
%load_ext autoreload
%autoreload 2

import pandas as pd
from rdkit import Chem
from rdkit.Chem import Draw
from IPython.display import display

import sys
sys.path.append('../scripts')
from data_utils import data_summary, load_csv_info

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [77]:
print("\n===================== vispils-v1.csv ====================\n")
load_csv_info('../../vispils/data/vispils-v1.csv')
print("\n===================== data_vispils.csv ====================\n")
load_csv_info('../../vispils/data/data_vispils.csv')

===================== vispils-v1.csv ====================

File: vispils-v1.csv
Size: 333.40 MB
Rows: 337,289
Columns: 88
Column Names: ['Iso SMILES', 'GC Pred.', 'aSMILES', 'afam1', 'afam_class', 'aCenterValence', 'aElectronegativity', 'aCenterSize', 'aSymmetry', 'aOxyAnions', 'aDipole', 'cfam', 'cfam1', 'cfam_class', 'cfamVolume', 'ctailVolume', 'cHeadVertex', 'cHeteroAtom', 'cFGs', 'cFGsGroup', 'aMolLogP', 'aMolMR', 'aMolWt', 'aNumHBA', 'aNumHBD', 'aRings', 'aVolume', 'aAsphericity', 'aEccentricity', 'aInertialShapeFactor', 'aPBF', 'aPMI1', 'aPMI2', 'aPMI3', 'aNPR1', 'aNPR2', 'aRadiusOfGyration', 'aSpherocityIndex', 'aLabuteASA', 'aTPSA', 'aAliCC', 'aAliHC', 'aAliRings', 'aAroCC', 'aAroHC', 'aAroRings', 'aNumNHOH', 'cMolLogP', 'cMolMR', 'cMolWt', 'cNumHBA', 'cNumHBD', 'cRings', 'cVolume', 'cAsphericity', 'cEccentricity', 'cInertialShapeFactor', 'cPBF', 'cPMI1', 'cPMI2', 'cPMI3', 'cNPR1', 'cNPR2', 'cRadiusOfGyration', 'cSpherocityIndex', 'cLabuteASA', 'cTPSA', 'cAliCC', 'cAliHC', 'cAliRings', 'cAroCC', 'cAroHC', 'cAroRings', 'cNumNHOH', 'Dataset', 'Log viscosity', 'Temperature', 'cSMILES', 'Anion|cfam', 'Anion|cFGsGroup', 'Anion|cfam|cFGsGroup', 'Anion|cfam_class', 'afam_class|cfam_class', 'Validated', 'Vm', 'DataSource', 'Reliability', 'η (mPas)']

===================== data_vispils.csv ====================

File: data_vispils.csv
Size: 3.08 MB
Rows: 20,252
Columns: 12
Column Names: ['Dataset', 'Iso SMILES', 'cSMILES', 'aSMILES', 'Pressure', 'Temperature', 'Log viscosity', 'Viscosity', 'cfam', 'afam', 'cvolume', 'avolume']

(3.080571174621582,
 20252,
 12,
 ['Dataset',
  'Iso SMILES',
  'cSMILES',
  'aSMILES',
  'Pressure',
  'Temperature',
  'Log viscosity',
  'Viscosity',
  'cfam',
  'afam',
  'cvolume',
  'avolume'])

## vispils-v1.csv

In [73]:
load_csv_info('../../vispils/data/vispils-v1.csv')

File: vispils-v1.csv
Size: 333.40 MB
Rows: 337,289

(333.40112686157227, 337289)

In [63]:
df = pd.read_csv('../../vispils/data/vispils-v1.csv')

In [64]:
data_summary(df)

,Iso SMILES,GC Pred.,aSMILES,afam1,afam_class,aCenterValence,aElectronegativity,aCenterSize,aSymmetry,aOxyAnions,...,Anion|cfam,Anion|cFGsGroup,Anion|cfam|cFGsGroup,Anion|cfam_class,afam_class|cfam_class,Validated,Vm,DataSource,Reliability,η (mPas)
0,BrC=C(Br)Cn1cc[n+](CC(Br)CBr)c1.Br[Al-](Br)(Br)Br,NaN,Br[Al-](Br)(Br)Br,mln,mln,4,1.61,36.617633,2,0,...,Br[Al-](Br)(Br)Br|im,Br[Al-](Br)(Br)Br|C=C|-Br,Br[Al-](Br)(Br)Br|im|C=C|-Br,Br[Al-](Br)(Br)Br|Aromatic,mln|Aromatic,NaN,0.351000,Pred.,Low,753.022822
1,BrC=C(Br)Cn1cc[n+](CC(Br)CBr)c1.Br[Fe-](Br)(Br)Br,NaN,Br[Fe-](Br)(Br)Br,mln,mln,4,1.83,41.051585,2,0,...,Br[Fe-](Br)(Br)Br|im,Br[Fe-](Br)(Br)Br|C=C|-Br,Br[Fe-](Br)(Br)Br|im|C=C|-Br,Br[Fe-](Br)(Br)Br|Aromatic,mln|Aromatic,NaN,0.352808,Pred.,Low,1604.314699
2,BrC=C(Br)Cn1cc[n+](CC(Br)CBr)c1.Brc1ccc2[n-]cn...,NaN,Brc1ccc2[n-]cnc2c1,cyc,cyc,2,3.04,15.598531,0,0,...,Brc1ccc2[n-]cnc2c1|im,Brc1ccc2[n-]cnc2c1|C=C|-Br,Brc1ccc2[n-]cnc2c1|im|C=C|-Br,Brc1ccc2[n-]cnc2c1|Aromatic,cyc|Aromatic,NaN,0.345080,Pred.,Low,5017.893461
3,BrC=C(Br)Cn1cc[n+](CC(Br)CBr)c1.C=C1O[B-](F)(F...,NaN,C=C1O[B-](F)(F)OC1=C,b,mln,4,2.04,17.808759,0,0,...,C=C1O[B-](F)(F)OC1=C|im,C=C1O[B-](F)(F)OC1=C|C=C|-Br,C=C1O[B-](F)(F)OC1=C|im|C=C|-Br,C=C1O[B-](F)(F)OC1=C|Aromatic,mln|Aromatic,NaN,0.324456,Pred.,Low,808.063339
4,BrC=C(Br)Cn1cc[n+](CC(Br)CBr)c1.C=C[B-](F)(F)F,NaN,C=C[B-](F)(F)F,b,mln,4,2.04,17.808759,0,0,...,C=C[B-](F)(F)F|im,C=C[B-](F)(F)F|C=C|-Br,C=C[B-](F)(F)F|im|C=C|-Br,C=C[B-](F)(F)F|Aromatic,mln|Aromatic,NaN,0.296576,Pred.,Low,1316.981492

Number of data points: 337289
Number of unique ILs: 337274
Unique Temperatures (8): [298.15 298.   298.2  298.1  298.13 298.24 298.3  298.05]
Columns (25): ['Anion|cFGsGroup', 'Anion|cfam', 'Anion|cfam_class', 'Anion|cfam|cFGsGroup', 'DataSource', 'Dataset', 'GC Pred.', 'Iso SMILES', 'Log viscosity', 'Reliability', 'Temperature', 'Validated', 'Vm', 'aAliCC', 'aAliHC', 'aAliRings', 'aAroCC', 'aAroHC', 'aAroRings', 'aAsphericity', 'aCenterSize', 'aCenterValence', 'aDipole', 'aEccentricity', 'aElectronegativity']

In [65]:
print(df['DataSource'].unique())
df.groupby('DataSource').size()

['Pred.' 'Exp.']

DataSource
Exp.       1959
Pred.    335330
dtype: int64

## data_vispils.csv

In [55]:
df = pd.read_csv('../../vispils/data/data_vispils.csv')

In [60]:
data_summary(df)

,Dataset,Iso SMILES,cSMILES,aSMILES,Pressure,Temperature,Log viscosity,Viscosity,cfam,afam,cvolume,avolume
0,ILthermo,CN(C)C=O.O=S(=O)([N-]S(=O)(=O)C(F)(F)F)C(F)(F)F,CN(C)C=O,O=S(=O)([N-]S(=O)(=O)C(F)(F)F)C(F)(F)F,0.10135,273.15,2.030195,107.20,,ntf,0.063976,0.155344
1,ILthermo,CN(C)C=O.O=S(=O)([N-]S(=O)(=O)C(F)(F)F)C(F)(F)F,CN(C)C=O,O=S(=O)([N-]S(=O)(=O)C(F)(F)F)C(F)(F)F,0.10135,278.15,1.900367,79.50,,ntf,0.063976,0.155344
2,ILthermo,CN(C)C=O.O=S(=O)([N-]S(=O)(=O)C(F)(F)F)C(F)(F)F,CN(C)C=O,O=S(=O)([N-]S(=O)(=O)C(F)(F)F)C(F)(F)F,0.10135,283.15,1.782473,60.60,,ntf,0.063976,0.155344
3,ILthermo,CN(C)C=O.O=S(=O)([N-]S(=O)(=O)C(F)(F)F)C(F)(F)F,CN(C)C=O,O=S(=O)([N-]S(=O)(=O)C(F)(F)F)C(F)(F)F,0.10135,288.15,1.675778,47.40,,ntf,0.063976,0.155344
4,ILthermo,CN(C)C=O.O=S(=O)([N-]S(=O)(=O)C(F)(F)F)C(F)(F)F,CN(C)C=O,O=S(=O)([N-]S(=O)(=O)C(F)(F)F)C(F)(F)F,0.10135,293.15,1.578983,37.93,,ntf,0.063976,0.155344

Number of data points: 20252
Number of unique ILs: 2951
Unique Temperatures (25): [253.0, 253.15, 253.2, 258.15, 259.9, 262.61, 262.7, 263.1, 263.15, 263.42, 264.05, 264.25, 264.5, 264.9, 265.1, 265.65, 265.94, 266.6, 266.77, 267.3, 267.59, 268.0, 268.15, 268.41, 269.1]
Columns (12): Index(['Dataset', 'Iso SMILES', 'cSMILES', 'aSMILES', 'Pressure',
       'Temperature', 'Log viscosity', 'Viscosity', 'cfam', 'afam', 'cvolume',
       'avolume'],
      dtype='object')